name = "HHMC-ATM10"
author = "Waveformal"
version = "1.0.0-ATM2.41"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "4005919dd118f78aacbd11e856d54f83f9bb6da7da7b15c0cc7c56ec613654d9"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.133"
