name = "HHMC-ATM10"
author = "Waveformal"
version = "1.0.0-ATM2.41"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "2a1e1700ab08c1a04fcaef7f884fb3943d699f9a10cf185878311a87ca0e6e84"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.133"
