name = "HHMC-ATM10"
author = "Waveformal"
version = "1.0.0-ATM2.41"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "f7b33c089806175c24456f3262641798498b438eeed06d26b9dac028dd4cf44c"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.133"
