name = "HHMC-ATM10"
author = "Waveformal"
version = "1.0.0-ATM2.41"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "c5f6d1c416e74c886315827b973e0ee4ed278264fa364d2202bbdc3a86957e41"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.133"
