name = "HHMC-ATM10"
author = "Waveformal"
version = "1.0.0-ATM2.41"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "cbfcc5b2155123a72d8444e64ad85c5f4bed686b8a0aebebaa31600cc8e4b014"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.133"
